server {
    listen 80;
    listen [::]:80;
    server_name ajuda.geolimites.com.br;

    root /var/www/geolimites-ajuda;
    index index.html;

    access_log /var/log/nginx/geolimites-ajuda.access.log;
    error_log /var/log/nginx/geolimites-ajuda.error.log;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
