CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS tab_roles (
    role_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT ck_roles_name CHECK (name IN ('ROLE_ADMIN', 'ROLE_USER'))
);

CREATE TABLE IF NOT EXISTS tab_users (
    user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(100),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    owner_id UUID,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_owner FOREIGN KEY (owner_id) REFERENCES tab_users(user_id)
);

CREATE TABLE IF NOT EXISTS tab_users_roles (
    user_id UUID NOT NULL,
    role_id UUID NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_users_roles_user FOREIGN KEY (user_id) REFERENCES tab_users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_users_roles_role FOREIGN KEY (role_id) REFERENCES tab_roles(role_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(500) NOT NULL UNIQUE,
    expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_id UUID NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES tab_users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tab_audit_log (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(255) NOT NULL,
    entity VARCHAR(255) NOT NULL,
    entity_id VARCHAR(255),
    description VARCHAR(500),
    username VARCHAR(100),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tab_memorial_standards (
    standard_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    standard_text TEXT NOT NULL,
    prompt_template TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    owner_id UUID,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_memorial_standards_owner FOREIGN KEY (owner_id) REFERENCES tab_users(user_id)
);

CREATE TABLE IF NOT EXISTS tab_templates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    file_url VARCHAR(500) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    memorial_standard_id UUID,
    municipality VARCHAR(255),
    abnt_norm VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    owner_id UUID NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_templates_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'DRAFT')),
    CONSTRAINT fk_templates_owner FOREIGN KEY (owner_id) REFERENCES tab_users(user_id),
    CONSTRAINT fk_templates_standard FOREIGN KEY (memorial_standard_id) REFERENCES tab_memorial_standards(standard_id)
);

CREATE TABLE IF NOT EXISTS tab_files (
    file_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    original_name VARCHAR(255) NOT NULL,
    stored_name VARCHAR(255) NOT NULL,
    extension VARCHAR(20),
    content_type VARCHAR(100),
    size_bytes BIGINT NOT NULL,
    checksum_sha256 VARCHAR(64),
    disk_path VARCHAR(500) NOT NULL,
    owner_id UUID,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_files_owner FOREIGN KEY (owner_id) REFERENCES tab_users(user_id)
);

CREATE TABLE IF NOT EXISTS tab_properties (
    property_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    internal_code VARCHAR(50),
    owner_name VARCHAR(255) NOT NULL,
    owner_document VARCHAR(20),
    owner_id_number VARCHAR(20),
    owner_phone VARCHAR(20),
    owner_email VARCHAR(255),
    street VARCHAR(255) NOT NULL,
    number VARCHAR(20),
    complement VARCHAR(100),
    neighborhood VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(2) NOT NULL,
    zip_code VARCHAR(10),
    coordinate_system VARCHAR(100),
    datum VARCHAR(50),
    utm_zone VARCHAR(10),
    central_meridian VARCHAR(20),
    sirgas_e DECIMAL(15,4),
    sirgas_n DECIMAL(15,4),
    sirgas_source VARCHAR(255),
    total_area DECIMAL(15,4),
    total_perimeter DECIMAL(15,4),
    main_frontage DECIMAL(15,4),
    average_depth DECIMAL(15,4),
    registration_number VARCHAR(100),
    registry_office VARCHAR(255),
    registration_book VARCHAR(50),
    registration_page VARCHAR(50),
    registration_date DATE,
    property_type VARCHAR(50),
    zoning VARCHAR(100),
    floor_area_ratio DECIMAL(5,2),
    lot_coverage DECIMAL(5,2),
    north_boundary TEXT,
    south_boundary TEXT,
    east_boundary TEXT,
    west_boundary TEXT,
    observations TEXT,
    restrictions TEXT,
    user_id UUID NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_properties_user FOREIGN KEY (user_id) REFERENCES tab_users(user_id)
);

CREATE TABLE IF NOT EXISTS tab_property_landmarks (
    landmark_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    property_id UUID NOT NULL,
    landmark_name VARCHAR(50) NOT NULL,
    landmark_type VARCHAR(20) NOT NULL,
    coordinate_x DECIMAL(15,4) NOT NULL,
    coordinate_y DECIMAL(15,4) NOT NULL,
    coordinate_z DECIMAL(10,4),
    entrance_azimuth DECIMAL(8,4),
    exit_azimuth DECIMAL(8,4),
    previous_distance DECIMAL(15,4),
    description TEXT,
    landmark_material VARCHAR(100),
    sequence_order INTEGER NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_landmarks_property FOREIGN KEY (property_id) REFERENCES tab_properties(property_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tab_property_boundaries (
    boundary_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    property_id UUID NOT NULL,
    direction VARCHAR(20) NOT NULL,
    extension DECIMAL(15,4) NOT NULL,
    azimuth DECIMAL(8,4),
    adjacent_type VARCHAR(50) NOT NULL,
    adjacent_name VARCHAR(255) NOT NULL,
    adjacent_document VARCHAR(50),
    full_description TEXT,
    sequence_order INTEGER NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_boundaries_property FOREIGN KEY (property_id) REFERENCES tab_properties(property_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tab_property_documents (
    document_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    property_id UUID NOT NULL,
    document_type VARCHAR(50) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    description TEXT,
    file_path VARCHAR(500),
    file_size BIGINT,
    mime_type VARCHAR(100),
    uploaded_by UUID NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_documents_property FOREIGN KEY (property_id) REFERENCES tab_properties(property_id) ON DELETE CASCADE,
    CONSTRAINT fk_documents_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES tab_users(user_id)
);

CREATE TABLE IF NOT EXISTS tab_user_credits (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL UNIQUE,
    total_credits INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_credits_user FOREIGN KEY (user_id) REFERENCES tab_users(user_id) ON DELETE CASCADE,
    CONSTRAINT ck_user_credits_total_credits CHECK (total_credits >= 0)
);

CREATE TABLE IF NOT EXISTS tab_credit_transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    amount INTEGER NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_credit_transactions_user FOREIGN KEY (user_id) REFERENCES tab_users(user_id) ON DELETE CASCADE,
    CONSTRAINT ck_credit_transactions_type CHECK (transaction_type IN ('PURCHASE', 'USE')),
    CONSTRAINT ck_credit_transactions_amount CHECK (amount > 0)
);

CREATE TABLE IF NOT EXISTS tab_credit_purchases (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    amount_reais DECIMAL(10,2) NOT NULL,
    credits_purchased INTEGER NOT NULL,
    payment_provider VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_credit_purchases_user FOREIGN KEY (user_id) REFERENCES tab_users(user_id) ON DELETE CASCADE,
    CONSTRAINT ck_credit_purchases_amount_reais CHECK (amount_reais > 0),
    CONSTRAINT ck_credit_purchases_status CHECK (status IN ('PENDING', 'PAID', 'FAILED')),
    CONSTRAINT ck_credit_purchases_credits_purchased CHECK (credits_purchased > 0)
);

CREATE INDEX IF NOT EXISTS idx_users_owner_id ON tab_users(owner_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_token ON refresh_tokens(token);
CREATE INDEX IF NOT EXISTS idx_memorial_standards_owner_id ON tab_memorial_standards(owner_id);
CREATE INDEX IF NOT EXISTS idx_templates_owner_id ON tab_templates(owner_id);
CREATE INDEX IF NOT EXISTS idx_templates_standard_id ON tab_templates(memorial_standard_id);
CREATE INDEX IF NOT EXISTS idx_files_owner_id ON tab_files(owner_id);
CREATE INDEX IF NOT EXISTS idx_properties_user_id ON tab_properties(user_id);
CREATE INDEX IF NOT EXISTS idx_properties_city_state ON tab_properties(city, state);
CREATE INDEX IF NOT EXISTS idx_properties_owner_name ON tab_properties(owner_name);
CREATE INDEX IF NOT EXISTS idx_properties_active ON tab_properties(active);
CREATE INDEX IF NOT EXISTS idx_landmarks_property_id ON tab_property_landmarks(property_id);
CREATE INDEX IF NOT EXISTS idx_landmarks_property_order ON tab_property_landmarks(property_id, sequence_order);
CREATE INDEX IF NOT EXISTS idx_boundaries_property_id ON tab_property_boundaries(property_id);
CREATE INDEX IF NOT EXISTS idx_boundaries_property_order ON tab_property_boundaries(property_id, sequence_order);
CREATE INDEX IF NOT EXISTS idx_documents_property_id ON tab_property_documents(property_id);
CREATE INDEX IF NOT EXISTS idx_documents_type ON tab_property_documents(document_type);
CREATE INDEX IF NOT EXISTS idx_user_credits_user_id ON tab_user_credits(user_id);
CREATE INDEX IF NOT EXISTS idx_credit_transactions_user_id ON tab_credit_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_credit_transactions_user_created_at ON tab_credit_transactions(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_credit_purchases_user_id ON tab_credit_purchases(user_id);
CREATE INDEX IF NOT EXISTS idx_credit_purchases_status ON tab_credit_purchases(status);

CREATE OR REPLACE VIEW vw_properties_summary AS
SELECT
    p.property_id,
    p.registration_number,
    p.name,
    p.property_type,
    p.street,
    p.number,
    p.complement,
    p.neighborhood,
    p.city,
    p.state,
    p.zip_code,
    p.owner_name,
    p.owner_document,
    p.owner_email,
    p.owner_phone,
    p.total_area,
    p.total_perimeter,
    p.datum,
    p.coordinate_system,
    p.active,
    p.created_at,
    p.updated_at,
    p.user_id,
    1 AS total_owners,
    COALESCE(doc.document_count, 0) AS total_documents,
    0 AS total_files,
    0 AS total_dxf_files,
    ''::TEXT AS dxf_files_list,
    (
        p.street ||
        CASE WHEN p.number IS NOT NULL THEN ', ' || p.number ELSE '' END ||
        CASE WHEN p.complement IS NOT NULL THEN ', ' || p.complement ELSE '' END ||
        ' - ' || p.neighborhood ||
        ', ' || p.city || ' - ' || p.state ||
        CASE WHEN p.zip_code IS NOT NULL THEN ' - ' || p.zip_code ELSE '' END
    ) AS full_address,
    CASE
        WHEN p.registration_number IS NOT NULL
         AND p.street IS NOT NULL
         AND p.neighborhood IS NOT NULL
         AND p.city IS NOT NULL
         AND p.state IS NOT NULL
         AND p.owner_name IS NOT NULL
         AND p.owner_document IS NOT NULL THEN 'COMPLETO'
        ELSE 'INCOMPLETO'
    END AS completeness_status
FROM tab_properties p
LEFT JOIN (
    SELECT property_id, COUNT(*) AS document_count
    FROM tab_property_documents
    GROUP BY property_id
) doc ON doc.property_id = p.property_id
WHERE p.active = TRUE;
